# This is an example config the controller will see in a configmap
- name: provision-host
  matchHosts:
    managedBy: baremetal
    provisionState: available
  inputParameters:
    - name: hostId
      type: string
    - name: imageURL
      type: string
    - name: network
      type: string
  hostSetup:
    workflowRef:
      name: provision-host
  hostTeardown:
    workflowRef:
      name: deprovision-host
  clusterSetup: {}
  clusterTeardown: {}
